//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public int film_id { get; set; }
        public System.DateTime datetime { get; set; }
        public Nullable<int> rating { get; set; }
        public string content { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual film film { get; set; }
    }
}
