//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class film_list
    {
        public Nullable<int> FID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<short> length { get; set; }
        public string rating { get; set; }
        public string actors { get; set; }
    }
}
