//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranee
    {
        public int TraineeID { get; set; }
        public string Full_Name { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> ET_IQ { get; set; }
        public Nullable<int> ET_Gmath { get; set; }
        public Nullable<int> ET_English { get; set; }
        public string Training_Class { get; set; }
        public string Evaluation_Notes { get; set; }
    }
}
