//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public string id { get; set; }
        public string username { get; set; }
        public string gmail { get; set; }
        public string image { get; set; }
        public Nullable<int> admin { get; set; }
    }
}
