//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int contactid { get; set; }
        public string FirtName { get; set; }
        public string LastName { get; set; }
        public string Category { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Favorite { get; set; }
        public string Image { get; set; }
        public int UserID { get; set; }
    }
}
